"""empty message

Revision ID: f95e22e5433c
Revises: 305ddcf99735
Create Date: 2022-10-27 15:07:31.358576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95e22e5433c'
down_revision = '305ddcf99735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whiskey', sa.Column('age', sa.String(length=20), nullable=True))
    op.drop_column('whiskey', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whiskey', sa.Column('year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('whiskey', 'age')
    # ### end Alembic commands ###
